//locations

export const DEFAULT_LOCATION = 'DEFAULT_LOCATION';
export const MAP_REGION = 'MAP_REGION';
export const CHOOSEN_LOCATION = 'CHOOSEN_LOCATION';
export const CHOOSEN_REGION = 'CHOOSEN_REGION'; 
export const CHOOSEN_ADDRESS = 'CHOOSEN_ADDRESS';

//login
export const USER_DATA = 'USER_DATA';
export const USER_LOADING = 'USER_LOADING';
export const USER_SIGNED = 'USER_SIGNED';
export const DELIVERY_BOYS = 'DELIVERY_BOYS';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_DEFAULTS = 'USER_DEFAULTS';

//vendor

export const ADD_SHOPS = 'ADD_SHOPS';
export const SHOPS_PAGINATION = 'SHOPS_PAGINATION';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const ERASE_PRODUCTS = 'ERASE_PRODUCTS';
export const PRODUCTS_PAGINATION = 'PRODUCTS_PAGINATION';
export const CHANGE_PRODUCT = 'CHANGE_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_PRODUCT_2 = 'REMOVE_PRODUCT_2';
export const REMOVE_PRODUCT_3 = 'REMOVE_PRODUCT_3';
export const ALGOLIA_TEXT = 'ALGOLIA_TEXT';
export const ALGOLIA_REFRESHING = 'ALGOLIA_REFRESHING';


//cart

export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const REMOVE_UNITS = 'REMOVE_UNITS';
export const REMOVE_UNITS_2 = 'REMOVE_UNITS_2';
export const INITIAL_CART = 'INITIAL_CART';
export const INITIAL_ORDER = 'INITIAL_ORDER';
export const CHANGE_ORDER = 'CHANGE_ORDER';
export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDERS = 'ADD_ORDERS';
export const ORDERS_PAGINATION = 'ORDERS_PAGINATION';
export const ORDERS_REFRESHING = 'ORDERS_REFRESHING';
export const UPDATE_ORDERS = 'UPDATE_ORDERS';
export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const UPDATE_FAVOURITES = 'UPDATE_FAVOURITES';
export const FAVOURITES_PAGINATION = 'FAVOURITES_PAGINATION';
export const FAV_REFRESHING = 'FAV_REFRESHING';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const ORDERS_FAVOURITE = 'ORDERS_FAVOURITE';
export const REMOVE_ORDER = 'REMOVE_ORDER';

//address

export const USER_ADDRESSES = 'USER_ADDRESSES';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';