name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - develop
    types: [opened]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.13.1'

      - name: Navigate to Storegrab directory
        run: cd Storegrab

      - name: Install Dependencies
        run: cd Storegrab && npm install

      - name: Run Tests
        run: cd Storegrab && npm test -- -u
